### ISSUE TITLE
Using European Server?

### ISSUE THREAD

**Issue by hopfi2k** [MickMake/GoSungrow#5]
Does GoSungrow support access via European Server as well? If so, how to specify EU-Server?

Using the default server (host) gives me a 

`ERROR: Account does not exist '账号不存在'`

**Comment by MickMake** [comment]
Could you try the latest version just released? v3.0.0

**Comment by hopfi2k** [comment]
Tried latest release and getting:

```
./GoSungrow api login                                                                                       
Error: API httpResponse is 404 Not Found
Usage:
  GoSungrow api login [flags]

Examples:
	GoSungrow api login  


Flags: Use "GoSungrow help flags" for more info.

Additional help topics:

ERROR: API httpResponse is 404 Not Found
```

host is correctly set to: https://api.isolarcloud.eu

Created the config file before of course...

Any idea?

**Comment by DrLEEi** [comment]
I myself use a European server.
It didn't work for me with the previous version either, but the current version (Current version: 3.0.1) started and works!
In my Home Assistant configuration: https://gateway.isolarcloud.eu

I can extract real-time and daily data.

I am very grateful for the work, because until now I have not been able to do this with anything else.
Unfortunately, the ModbusTCP communication did not work either.

**Comment by hopfi2k** [comment]
Changing host to https://gateway.isolarcloud.eu did the trick. Many thanks!

**Comment by MickMake** [comment]
Fantastic! Great to hear it's working well.
