### ISSUE TITLE
Found SunGrow 0 devices

### ISSUE THREAD

**Issue by haozgit** [MickMake/GoSungrow#70]
Hi, im facing this issue and there is only limited sensor being detected. anyone facing the same issue ? thanks.
<img width="828" alt="sungrow2" src="https://github.com/MickMake/GoSungrow/assets/74980013/446415fb-eb6b-4502-a1de-8b5bf6738768">
<img width="525" alt="sungrow1" src="https://github.com/MickMake/GoSungrow/assets/74980013/74e7734a-ddc6-4a62-ad2e-901c784869d7">

**Comment by sicablondu** [comment]
i see this issue closed, but how was it solved?

**Comment by sicablondu** [comment]
> i see this issue closed, but how was it solved?

apparently i had to user the Owner account , login the iSolarCloud, browse a bit through Live data and then it started to pull data

**Comment by Paraphraser** [comment]
Interesting. My Sungrow inverter was installed in Feb 2023. Between then and now I have never logged into iSolarCloud using a browser. I can be sure of that because my keychain doesn't have the password entry that would have been created as a by-product.

On the day my inverter was installed, everything was set up via my iPad and the installer's Android phone. I got GoSungrow working about two weeks later. Since then, with the exception of the brief period when GoSungrow stopped working because of the change of API key etc, everything has "just worked".

All of my interactions have been via either the iPad app or GoSungrow. If there are features, widgets or other controls that can only be accessed via a browser, thus far I've never had any need for them.

Either my experience makes me a very lucky exception to the rule that a browser login is necessary before GoSungrow can pull data, or that isn't the full explanation.

In issue #136, @WhiteLion13 was having trouble with GoSungrow when loggjng-in as an "installer" but resolved that by logging-in as an ordinary user. I think that probably fits with what you say about an "owner" account. I had not focused on the word "owner" before but I now realise that's the label I see in the iSolarCloud app.

Here's a theory which I think fits your experience, my experience, and that of @WhiteLion13 in #136: **some** interaction is required with **either** a browser login (your experience) or login using the iSolarCloud app (my experience) with **owner** credentials (all three of us), and it is that interaction which primes the data-pump for GoSungrow.

You will confound that theory if you report having used the iSolarCloud app with owner credentials before you solved the problem by using a browser to login as an owner. There are so many issues with this problem at the core (#136, #132, #111, #101, #54, #18) that it would be great if this theory turned out to be the answer.
